"""empty message

Revision ID: 6df1b6302756
Revises: 9e76049419c2
Create Date: 2023-04-23 12:02:22.950105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df1b6302756'
down_revision = '9e76049419c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'genero', ['genero_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('genero_id')

    # ### end Alembic commands ###
