DEBUG = True

USERNAME = 'root'
PASSWORD = '#Fbrql823'
SERVER = 'localhost'
DB = 'catalogo_jogos'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SECRET_KEY = 'fbrql823'
